### ISSUE TITLE
Pulling watchtower fails

### ISSUE THREAD

**Issue by jtme** [imjustleaving/trueNAS#10]
ERROR: Get "https://registry-1.docker.io/v2/containrrr/watchtower/manifests/ ....

results in 
Prowlarr configuration file not found.
Sonarr configuration file not found.
Radarr configuration file not found.

**Comment by serversathome-personal** [comment]
could you give more some more context of how this error was generated?

**Comment by jtme** [comment]
sure- when Setting Up the VM - and running the script1.sh - all things are ok until i see this error i posted. 

Status: Downloaded newer image for lscr.io/linuxserver/sonarr:latest
Pulling watchtower (containrrr/watchtower:)...
ERROR: Get "https://registry-1.docker.io/v2/containrrr/watchtower/manifests/sha2[_REDACTED_]": dial tcp [2600:1f18:2148:bc01:20a3:9c3e:d4a7:9fb]:443: connect: network is unreachable

**Comment by serversathome-personal** [comment]
i have never seen that error before. i double checked the script and the section of the docker compose file for watchtower is correct and up-to-date. could you try running it again? also the complete output from the script may prove to be helpful...

**Comment by jtme** [comment]
I was not able to solve this, rebuilding fresh VM gave errors at other points, hence i believe its my issue and closing to avoid unnecessary work. ill look into more manual approach

**Comment by serversathome-personal** [comment]
try checking out this wiki for more step by step instructions

[new wiki](https://wiki.hydrology.cc/en/home)
