### ISSUE TITLE
Root access required

### ISSUE THREAD

**Issue by tyler72us** [imjustleaving/trueNAS#3]
Hey I love your guide. Thanks for doing it!  I'm running into an issue on the HeavyScripts portion. When I try to run the script the shell says I need to run it as root.  Even if I run it with sudo.

**Comment by serversathome-personal** [comment]
are u on this part? https://github.com/imjustleaving/trueNAS/wiki/A-Guide-to-go-from-a-bare-metal-TrueNAS-Scale-install-to-a-Fully-Automated-Media-Server#heavyscript

if u are, do u mean where u do the curl command or after u add a cron job?

**Comment by tyler72us** [comment]
curl command.  I know iX has been trying to eliminate root, so maybe related to that?

**Comment by serversathome-personal** [comment]
when u go to System Settings > Shell, by default truenas opens as root. however, i realize i may have made a mistake in the guide by telling users to switch the the '/' directory. ive updated the guide; go through the steps again and tell me if that solves it. if not, send screenshots with ur next post so i can see what is going on.

**Comment by tyler72us** [comment]
Sorry for the delay. Attached is a screenshot
![Uploading Screenshot 2023-07-26 150156.png…]()

**Comment by tyler72us** [comment]
![Screenshot 2023-07-26 150156](https://github.com/imjustleaving/trueNAS/assets/46353953/a3533215-1278-4ee6-9a69-2aec7f3c3fe7)

**Comment by serversathome-personal** [comment]
it looks like you ssh in through a terminal. could you try to run the curl command from the truenas GUI interface through **System Settings** -> **Shell**? i have the suspicion admin@truenas is not being treated the same as root@truenas, which is what the default shell gives u with the # for root permissions.

**Comment by tyler72us** [comment]
unfortunately that is the shell from the GUI
![Screenshot 2023-07-26 154728](https://github.com/imjustleaving/trueNAS/assets/46353953/e2301584-9e84-415f-a2eb-8e28958e31d6)

**Comment by serversathome-personal** [comment]
huh. did u setup an admin user separately? it would definitely help if u logged in as root instead of admin.

**Comment by tyler72us** [comment]
I mean I might be able to but,
"Starting with SCALE Bluefin 22.12.0, root account logins are deprecated for security hardening and to comply with Federal Information Processing Standards (FIPS). All TrueNAS users should [create a local administrator account](https://www.truenas.com/docs/scale/scaletutorials/credentials/managelocalusersscale/) with all required permissions and begin using it to access TrueNAS. When the root user password is disabled, only an administrative user account can log in to the TrueNAS web interface.

A future update of TrueNAS SCALE will permanently disable root account access."

https://www.truenas.com/docs/scale/gettingstarted/configure/firsttimelogin/

**Comment by serversathome-personal** [comment]
ive never done this with anything but the root user. def check ur permissions since thats the error youre getting. did u give your admin user sudo permissions (check box)? 

![image](https://github.com/imjustleaving/trueNAS/assets/109609649/c42a0233-a6cd-44b0-a21c-3abf73b0e274)

**Comment by tyler72us** [comment]
Yep, that box was already checked

**Comment by serversathome-personal** [comment]
when you go to system settings > shell, could u enter the command 'pwd' and send the output please?

**Comment by tyler72us** [comment]
/home/admin

**Comment by serversathome-personal** [comment]
youre going to want to enter the command `cd /root` then try the curl command from there.

**Comment by tyler72us** [comment]
Access denied. IX has been shutting off root access.  That's what that link
I sent was for.  I even added the admin user to the root group.

**Comment by serversathome-personal** [comment]
so i just tried adding a test user. this is my users aux groups:  sudo, builtin_administrators, builtin_users, root
the shell i have selected is bash
i checked the box for Allow all sudo commands.

then i executed the following commands from the shell:

`sudo su`
`cd /root`
`curl -s https://raw.githubusercontent.com/Heavybullets8/heavy_script/main/functions/deploy.sh | bash && source "$HOME/.bashrc" 2>/dev/null && source "$HOME/.zshrc" 2>/dev/null`

see if that works for you.

**Comment by tyler72us** [comment]
That did it!  Thanks!
