### ISSUE TITLE
/mnt/media or /media?

### ISSUE THREAD

**Issue by voxie12** [imjustleaving/trueNAS#4]
I am a completely noob to TrueNAS. First time using truenas since 31 augest.
I am using your "TrueNAS Media Server Virtual Machine" guide.
I checked everything in your script1.sh. 
I am a bit confused.

Should I path this or that?
![image](https://github.com/imjustleaving/trueNAS/assets/65469239/47644a45-71d6-4962-96b5-8a9d7b30182b)
or
![image](https://github.com/imjustleaving/trueNAS/assets/65469239/9fe7c345-76b8-4500-835e-e4222f32ed02)

thanks

**Comment by serversathome-personal** [comment]
your nfs share should be /mnt/thor. in the thor pool you need to have the following directories: /mnt/thor/media/movies, /mnt/thor/media/tv, /mnt/thor/media/downloads. when you run the script, your TRUENAS_IP needs to be the IP of your truenas server, the pool name is /mnt/thor.

also make sure the permissions on those datasets as well as /mnt/thor/configs is correct. it needs to look like this:

![image](https://github.com/imjustleaving/trueNAS/assets/109609649/2db05218-df37-48d8-9352-aefc62c0ed13)

![image](https://github.com/imjustleaving/trueNAS/assets/109609649/3a909dac-34f5-46be-bef8-0a8df661a419)

**Comment by voxie12** [comment]
ok, thank you, i enabled both nfs and smb, i put some movies in the folder from smb but i couldnt see it in the nfs share? i mounted nfs on ubuntu server and there was nothing when i already put some movies in the smb folder? is it possible to share both at same time?

**Comment by serversathome-personal** [comment]
dont do simultaneous smb + nfs share on the same dataset. stick with one or the other. if u are mounting the share in a linux machine, go with nfs.
