### ISSUE TITLE
Can't make account on new wiki; trying to add comment.

### ISSUE THREAD

**Issue by d1ddle** [imjustleaving/trueNAS#7]
Account creation failed- mail server not setup so could not receive confirmation email.
The comment in question was to thank you for the work you're doing, and to suggest adding the apps onto an NFS share instead of via HostPath, purely due to how I like to use a Samba share in conjunction and HostPath has caused me many a headaches prior.
All the best.
PS: What hardware are you using? I'd love to know whether it's a regular desktop or like a dedicated dell machine + specs.

**Comment by serversathome-personal** [comment]
thanks so much for the kind comments and heads up! i have disabled the local auth and went with discord and github for sign ups. could you try again? i need a tester lol. 

i dont like the nfs share as a way to mount the file path in the container. there is a lot of controversy around that methodology. i use those same directories as nfs shares to my daily driver and writing to the directory from 2 sources simultaneously is advised against. hence why i go with host-path. but for someone only sharing those directories with the containers - it would work just fine.

for more info on my hardware check out [this post.](https://servers.hydrology.cc/2023/08/08/what-i-use/)

**Comment by d1ddle** [comment]
Account auth worked with github. No idea where I actually left my comment though 😂
Doh looks like I left it in the request new content section... mb
