### ISSUE TITLE
Might Seem Like a Stupid Question But Do you have a link to a faq on how to get sonarr and radarr to delete sample files 

### ISSUE THREAD

**Issue by ghost** [imjustleaving/trueNAS#9]
Might Seem Like a Stupid Question But Do you have a link to a faq on how to get sonarr and radarr to delete sample files

**Comment by serversathome-personal** [comment]
the closest thing i could find to this was an app called qbitrr which does delete non playable files.

[https://github.com/Feramance/Qbitrr](https://github.com/Feramance/Qbitrr)
